### ISSUE TITLE
html, css 예쁘게

### ISSUE THREAD

**Issue by Zzangeun** [DB-Prof-Aziz-Project/movie_review#16]
- [x] 메인
- [x] 검색
- [x] 카테고리
- [x] 감상평 create, update
- [x] 나의 감상평
- [x] 감상평 detail
- [x] 영화 detail
- [x] 로그인
- [x] 회원가입

**Comment by rnjswngus275** [comment]
<해결못한부분>
메인 포스터 중간정렬 어떻게 해?
장르별 모아보기 장르와 포스터 분리 어떻게 해?
제출 버튼 어디에 있는거 ? 로그인부분 제출버튼이랑 login이랑 연결 

<덜한부분>
상세페이지 꾸미기 
실패 창 꾸미기
로그인 배경 색갈 바꾸기
나의 감상평 부분
감상평 수정 부분

**Comment by Zzangeun** [comment]
<해결못한부분>

- [x] 메인 포스터 중간정렬 어떻게 해?
- [x] 장르별 모아보기 장르와 포스터 분리 어떻게 해?
- [x] 제출 버튼 어디에 있는거 ? 로그인부분 제출버튼이랑 login이랑 연결

**Comment by Zzangeun** [comment]
- [x] 메인 타이틀 배경 이미지 바꿈

**Comment by rnjswngus275** [comment]
- [x] 버튼 ui바꾸기

- [x] [my review]내가 영화 본 시간 네모 박스안에 글씨가 안커지냐 왜

- [x] [my review]> [감상평 자세히 보기] 감상평 수정, 삭제 a로 하던지 버튼으로 하던지 통일

- [x] [회원가입] 관심장르 체크박스 두줄로 만들기

- [x] [영화 자세히 보기] 일부러 오른쪽에 영화정보 붙인건지 물어보기

**Comment by Zzangeun** [comment]
주현이 열심히 하넹 홧팅홧팅!!!! 🤹🏻
